### PR TITLE
Update documentation, dependencies & fix audit warnings

### PR DESCRIPTION
**Pull request by rheaditi**
* Ran `npm audit --fix` and "clean" `npm install`. Updates the lockfile accordingly.
* Update docs, rename to pivotal-lint [#169931786] (#21)

### CODE REVIEW

**Comment by rajanand02** [comment]
Draft? Something new from GitHub?

**Comment by rajanand02** [comment]
@rheaditi if you are cleaning up pr-lint please check the GITHUB_ACCESS_TOKEN input we are taking. GitHub by default supports GITHUB_TOKEN env variable. I might have made the mistake of adding the token with a different name.

**Comment by rheaditi** [comment]
> @rheaditi if you are cleaning up pr-lint please check the GITHUB_ACCESS_TOKEN input we are taking. GitHub by default supports GITHUB_TOKEN env variable. I might have made the mistake of adding the token with a different name.

Sure. I'll do them in a separate PR..

**Comment by rajanand02** [comment]
@rheaditi why is there a lint change in index.js file? It is a generated file, how come no change in the source but only only the generated file?

**Pull request merged**
